// flow-typed signature: c4bc09e1edcd355f61e091b85af4f9b9
// flow-typed version: <<STUB>>/react-close-on-escape_v^1.0.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-close-on-escape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-close-on-escape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-close-on-escape/dist/index' {
  declare module.exports: any;
}

declare module 'react-close-on-escape/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-close-on-escape/dist/index.js' {
  declare module.exports: $Exports<'react-close-on-escape/dist/index'>;
}
declare module 'react-close-on-escape/src/index.js' {
  declare module.exports: $Exports<'react-close-on-escape/src/index'>;
}
